# Generated by Django 4.1.2 on 2022-12-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deporte',
            name='imagen',
            field=models.ImageField(default='/media/imagenes/default.jpg', upload_to=''),
        ),
    ]
