# Generated by Django 4.1.2 on 2022-12-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_deporte_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='articulos'),
        ),
        migrations.AlterField(
            model_name='deporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='deportes'),
        ),
    ]
