# Generated by Django 4.1.2 on 2022-12-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_mensajes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajes',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
